In [1]:
import numpy as np

### Задание 1

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2

In [7]:
a1 = a.reshape(6, 2)
a2 = a.reshape(3, 4)
a3 = a.reshape(2, 6)
a4 = a.reshape(12, 1)
a5 = a.reshape(4, 3)


### Задание 3

In [14]:
a1 = a.reshape(-1, 2)
a2 = a.reshape(-1, 4)
a3 = a.reshape(2, -1)
a4 = a.reshape(12, -1)
a5 = a.reshape(3, -1)


### Задание 4

In [15]:
#Нет, массив из одного столбца и 12 строк не одномерный. Пример: 
a = np.arange(12, 24)
a1 = a.reshape(12, 1)

print(a)
print(a1)

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 5

In [16]:
a = np.random.randn(3,4)
a

array([[-0.92213761,  0.10656888,  0.78864722, -1.77417119],
       [ 0.81361763,  0.72592974, -0.1026404 , -1.71588159],
       [-1.62541359,  0.01054495,  0.21491779,  0.71216849]])

In [17]:
a1 = a.flatten()
a1

array([-0.92213761,  0.10656888,  0.78864722, -1.77417119,  0.81361763,
        0.72592974, -0.1026404 , -1.71588159, -1.62541359,  0.01054495,
        0.21491779,  0.71216849])

### Задание 6

In [20]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

In [22]:
b = a.reshape(1,10)
b
#массив b становится двумерным

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

### Задание 8

In [27]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.vstack((a,b))
v.size

10

### Задание 9

In [29]:
a = np.arange(0, 12)

A = a.reshape(4, 3)
print(A)

At = A.transpose()
print(At)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [32]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [34]:
B.shape

(4, 4)

In [37]:
#B_inv = np.linalg.inv(B)
#получим ошибку, т.к. это сингулярная матрица

### Задание 10

In [38]:
np.random.seed(42)

### Задание 11

In [39]:
a = np.random.randint(0, 16,16)

### Задание 12

In [40]:
C = a.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [41]:
D = (C*10) + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [42]:
D_det = np.linalg.det(D)
print('Определитель:', D_det)

D_rank = np.linalg.matrix_rank(D)
print('Ранг:', D_rank)

D_inv = np.linalg.inv(D)
print('Обратная матрица:', D_inv)

Определитель: -28511999.999999944
Ранг: 4
Обратная матрица: [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


### Задание 13

In [43]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [44]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])